FROM node:20-alpine AS Builder 
WORKDIR /app
COPY package* .
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /fe
COPY --from=Builder /app/build/ /fe/build/
RUN npm install -g serve
EXPOSE 3000
CMD [ "serve","-s","build","-l","3002"]
