kind: StatefulSet 
apiVersion: apps/v1
metadata:
  name: mysql-st
  namespace: wordpress

spec:
  serviceName: mysql-service
  replicas: 3
  selector:
    matchLabels:
      app: mysql 
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root 
        - name: MYSQL_DATABASE
          value: wordpress-db
        - name: MYSQL_USER
          value: wordpress 
        - name: MYSQL_PASSWORD 
          value: password 
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi        
