kind: Deployment 
apiVersion: apps/v1
metadata:
  name: wordpress-deployment
  namespace: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.2.1-apache
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: password
        - name: WORDPRESS_DB_NAME
          value: wordpress-db 
        volumeMounts:
        - name: wordpress-pv-storage
          mountPath: /var/www/html

      volumes: 
      - name: wordpress-pv-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc    