kind: Deployment 
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: backend 
  template:
    metadata:
      name: backend-pod
      namespace: chat-app
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: osamashahzad58/chat-app-backend:latest
        ports:
        - containerPort: 5001
        env: 
        - name: NODE_ENV
          value: production
        - name: MONGODB_URI
          value: "mongodb://mongoadmin:secret@mongo:27017/dbname?authSource=admin"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwt
              name: chat-app-secrets
        - name: PORT 
          value: "5001"
