kind: PersistentVolume 
apiVersion: v1 
metadata:
  name: mongodb-pv 
  namespace: chat-app
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: local-storage
  hostPath:
    path: /data    