kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-app-deployment
  namespace: nginx
  labels:
    app: react-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app

  template:
    metadata:
      name: react-app
      labels:
        app: react-app

    spec:
      containers:
      - name: react-app
        image: osamashahzad58/react-app
        ports:
        - containerPort: 3002
      