kind: Service
apiVersion: v1 
metadata:
  name: react-app-service
  namespace: nginx
spec:
  selector:
    app: react-app
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: ClusterIP  

